address/urls.py
from django.conf.urls import patterns, include, url
from address.views import (AddressListView, AddressDetailView, AddressUpdateView, 
						  AddressDeleteView, AddressCreateView)


urlpatterns = patterns('',

    url(r'^$', AddressListView.as_view(), name='address_list'),
    url(r'^new/$', AddressCreateView.as_view(), name='address_new'),
    url(r'^(?P<pk>\d+)/$', AddressDetailView.as_view(), name='address_item'),
    url(r'^edit/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address_edit'),
    url(r'^delete/(?P<pk>\d+)/$', AddressDeleteView.as_view(), name='address_delete'),

)

courses/urls.py
from django.conf.urls import patterns, include, url
from courses.views import (CoursesListView, CoursesDetailView, CoursesUpdateView, 
						  CoursesDeleteView, CoursesCreateView, 
						  GroupCreateView, GroupDeleteView, GroupUpdateView,
                          GroupDetailView)


urlpatterns = patterns('',

    url(r'^$', CoursesListView.as_view(), name='courses_list'),
    url(r'^(?P<pk>\d+)/$', CoursesDetailView.as_view(), name='courses_item'),
    url(r'^new/$', CoursesCreateView.as_view(), name='courses_new'),
    url(r'^edit/(?P<pk>\d+)/$', CoursesUpdateView.as_view(), name='courses_edit'),
    url(r'^delete/(?P<pk>\d+)/$', CoursesDeleteView.as_view(), name='courses_delete'),
    
    url(r'^new_group/$', GroupCreateView.as_view(), name='group_new'),
    url(r'^edit_group/(?P<pk>\d+)/$', GroupUpdateView.as_view(), name='group_edit'),
    url(r'^delete_group/(?P<pk>\d+)/$', GroupDeleteView.as_view(), name='group_delete'),
    url(r'^groups/(?P<pk>\d+)/$', GroupDetailView.as_view(), name='groups_item'),
)

pybursa/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

    url(r'^$', TemplateView.as_view(template_name='pybursa/base.html'), name='home'),
    url(r'^students/', include('students.urls'), name='students'),
    url(r'^courses/', include('courses.urls'), name='courses'),
    url(r'^coaches/', include('coaches.urls'), name='coaches'),
    url(r'^address/', include('address.urls'), name='address'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cv/', TemplateView.as_view(template_name='pybursa/cv.html'), name='cv'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models
import datetime


class Group(models.Model):
    name = models.CharField(max_length=30, null=True,
        blank=True)
    protect = models.BooleanField(
        default=False,
        help_text='protection from removal anonymous user',
    )
    start_date = models.DateField(default=datetime.date.today())
    end_date = models.DateField(null=True, blank=True)
    number_of_students = models.IntegerField(default=5)
    course = models.ForeignKey('courses.Course', null=True)
    
    def __init__(self, *args, **kwargs):
        super(Group, self).__init__(*args, **kwargs)
        self.end_date = (self.start_date + datetime.timedelta(days=61))
        try:
            self.name = ('%s %s-%s' % (
                        self.course.name,
                        self.start_date.strftime('%Y %b'),
                        self.end_date.strftime('%b'),
                        ))
        except AttributeError:
            pass

    def __unicode__(self):
        return '%s' % (self.name)

    def get_absolute_url(self):
        return "/courses/groups/%i/" % self.id


class Course(models.Model):
    TECNOLOGY_CHOISE = (
        ('python', 'Python'),
        ('ruby', 'Ruby'),
        ('javascript', 'JavaScript'),
    )
    LABEL_IMG = {
        'python': 'python label.png',
        'ruby': 'shiny_red_ruby.png',
        'javascript': 'js.png',
    }
    protect = models.BooleanField(
        default=False,
        help_text='protection from removal anonymous user',
    )
    name = models.CharField(max_length=15)
    description= models.TextField()
    coach = models.ForeignKey('coaches.Coach',  limit_choices_to={'status': 'coach'})
    assistant = models.ForeignKey('coaches.Coach', limit_choices_to={'status': 'assistant'}, blank=True, null=True,
                                  related_name='course_assistant')
    tecnology = models.CharField(max_length=11, choices=TECNOLOGY_CHOISE, default='')
    venue = models.ForeignKey('address.Address', related_name='course_venue', null=True, blank=True, on_delete=models.SET_NULL,
        default=None)

    def get_img(self):
        tec = self.tecnology
        return self.LABEL_IMG[tec]

    def get_absolute_url(self):
        return "/courses/%i/" % self.id

    def __unicode__(self):
        return '%s (%s) - %s' % (self.name, self.coach, self.tecnology)

students/models.py
# coding: utf8
# -*- coding: utf_8 -*-
from django.db import models
from courses.models import Course

class Student(models.Model):
    PACKAGE_CHOISES = (
        ('standart', 'Standart'),
        ('gold', 'Glod'),
        ('platimun', 'Platinum'),
    )
    name = models.CharField(max_length=15)
    surname = models.CharField(max_length=15)
    date_of_birth = models.DateField(blank=True, null=True)
    email = models.EmailField(default='example@mail.com')
    phone = models.CharField(max_length=15, blank=True)
    package = models.CharField(max_length=8, choices=PACKAGE_CHOISES,
                        blank=True, null=True)
    group = models.ManyToManyField('courses.Group', blank=True, null=True)
    courses = models.ManyToManyField('courses.Course', null=True, blank=True, editable=False)
    protect = models.BooleanField(
        default=False, 
        help_text='protection from removal anonymous user',
    )
     
    def __setattr__(self, *args, **kwargs):
        super(Student, self).__setattr__(*args, **kwargs)
        if 'group' in args[0]:
            courses_id = [course_id[0] for course_id in self.group.values_list('course_id').distinct()]
            super(Student, self).__setattr__('courses', Course.objects.filter(id__in=courses_id))


    def __init__(self, *args, **kwargs):
        super(Student, self).__init__(*args, **kwargs)
        
    def get_absolute_url(self):
        return "/students/%i/" % self.id


    def __unicode__(self):
        return u"%s %s" % (self.surname, self.name)

courses/views.py
# -*- coding: cp1251 -*-
from django.core.urlresolvers import reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from courses.models import Course, Group
from coaches.models import Coach
from address.models import Address
from django.forms import ModelForm

from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget
from django import forms

from django.utils.decorators import classonlymethod
from django.shortcuts import redirect
from django.contrib import messages

class GroupForm(ModelForm):
	class Meta:
		model = Group
		fields = ['course', 'start_date']
		widgets = {
            'start_date': SelectDateWidget(years=range(2014, 2020)),
        }

class GroupCreateView(CreateView):
	model = Group
	template_name = 'courses/group_edit.html'
	success_url = reverse_lazy('courses_list')
	form_class = GroupForm

class GroupDeleteView(DeleteView):
	model = Group
	success_url = reverse_lazy('courses_list')
	
	def render_to_response(self, context, **response_kwargs):
		if self.get_object().protect:
			messages.info(self.request, "Sory, you can't delete this object. It is protect by the administation.")
			return redirect(self.request.META.get('HTTP_REFERER','/'))
		return super(GroupDeleteView, self).render_to_response(context, **response_kwargs)


class GroupUpdateView(UpdateView):
	model = Group
	template_name  = 'courses/group_edit.html'
	form_class = GroupForm


class GroupDetailView(DetailView):
	model = Group
	template_name = 'courses/group_detail.html'
	context_object_name = 'group'

	def get_context_data(self, **kwargs):
  		context = super(GroupDetailView, self).get_context_data(**kwargs)
  		context['students'] = self.get_object().student_set.all()
  		return context


class CourseEditForm(ModelForm):
	class Meta:
		model = Course
		fields = ['name', 'tecnology', 'coach', 'assistant', 'venue', 'description']
		widgets = {
			'description': forms.Textarea,
			'tecnology': forms.RadioSelect,
		}


class CoursesListView(ListView):
	model = Course
	template_name = 'courses/courses_list.html'
	context_object_name = 'courses'


class CoursesDetailView(DetailView):
	model = Course
	template_name = 'courses/courses_item.html'
	context_object_name = 'course'
	
	def get_context_data(self, **kwargs):
  		context = super(CoursesDetailView, self).get_context_data(**kwargs)
  		# context['course'] = u'; '.join(self.get_object().course_venue.values_list('name', 
    	#                                                     flat=True))
		# print self.get_object()
		# print context['course'].student_set.all()[0].name
  		return context


class CoursesCreateView(CreateView):
	model = Course
	template_name = 'courses/courses_edit.html'
	success_url = reverse_lazy('courses_list')
	form_class = CourseEditForm

	def get_context_data(self, **kwargs):
  		context = super(CoursesCreateView, self).get_context_data(**kwargs)
  		context['coaches'] = Coach.objects.filter(status='coach')
  		context['assistants'] = Coach.objects.filter(status='assistant')
  		context['addresses'] = Address.objects.all()
  		return context

class CoursesUpdateView(UpdateView):
	model = Course
	template_name  = 'courses/courses_edit.html'
	form_class = CourseEditForm

	def get_context_data(self, **kwargs):
  		context = super(CoursesUpdateView, self).get_context_data(**kwargs)
  		context['coaches'] = Coach.objects.filter(status='coach')
  		context['assistants'] = Coach.objects.filter(status='assistant')
  		context['addresses'] = Address.objects.all()
  		return context

class CoursesDeleteView(DeleteView):
	model = Course
	success_url = reverse_lazy('courses_list')
	
	def render_to_response(self, context, **response_kwargs):
		if self.get_object().protect:
			messages.info(self.request, "Sory, you can't delete this object. It is protect by the administation.")
			return redirect(self.request.META.get('HTTP_REFERER','/'))
		return super(CoursesDeleteView, self).render_to_response(context, **response_kwargs)

templates/courses/course_confirm_delete.html
{% extends "courses/courses_base.html" %}
{% load static %}

{% block css %}{{ STATIC_URL }}courses/css/course_confirm_delete.css{% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <form action="" method="post">{% csrf_token %}
          <h3>Are you sure you want to delete {{ object.name }}
            {{ object.id }}</h3>
          <div class="btn-group" role="group" aria-label="...">
            <input type='submit' class='btn btn-danger' value="delete"/>
            <a href="{% url 'courses_list' %}" class="btn btn-default">cancel</a>
          </div>
        </form>
    </div>
{% endblock content %}

templates/courses/courses_base.html
{% extends "pybursa/base.html" %}
{% block massage %}
{% if messages %} {% for message in messages %}
    <div class="alert alert-danger">
      <a href="#" class="close pull-left" data-dismiss="alert">×</a>
      <p style="margin-left: 20px;">{{ message }}</p>
    </div>
 {% endfor %} {% endif %}
 {% endblock massage %}
{% block class-active-courses %} class="active" {% endblock %}

templates/courses/courses_edit.html
{% extends "courses/courses_base.html" %}
{% load static %}

{% block css %}{{ STATIC_URL }}courses_edit.css{% endblock %}


{% block content %}
<body>
    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Submit menu</button>
          </p>
          <div class="jumbotron">
            <h3>Editing course</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-inline">
                  <div class="form-group has-error has-feedback">
                    {% if form.name.errors %}
                      <ul class="control-label" for="id_{{ form.name.html_name }}">{{ form.name.errors }}</ul>
                    {% endif %}
                    {{ form.name.label_tag }}
                    <input type="text" class="form-control" id="id_{{ form.name.html_name }}" name="{{ form.name.html_name }}" placeholder="" maxlength="225" aria-describedby="inputError2Status" value="{{ form.name.value|default:'' }}">
                  </div>
                  <div class="form-group has-error has-feedback">
                      {% if form.tecnology.errors %}
                          <ul class="control-label" for="id_{{ form.tecnology.html_name }}">{{ form.tecnology.errors }}</ul>
                      {% endif %}
                      {% for radio in form.tecnology %}
                        <label class="radio-inline">
                          <input type="radio" id="id_{{ form.tecnology.html_name }}" name="{{ radio.name }}" value="{{ radio.value }}">{{ radio }}
                        </label>
                      {% endfor %}
                  </div>
                </div>
                <br>
                <div class="form-horizontal">
                  {{ form.coach.errors }}
                  {{ form.coach.label_tag }}
                  <select id="id_{{ form.coach.html_name }}" name="{{ form.coach.html_name }}" class="form-control">
                      {% for coach in coaches %}
                          <option value="{{ coach.id }}"  
                          {% if coach.id == form.coach.value|get_digit:"1"%}
                            selected="selected" {% endif %}>{{ coach }}</option>
                          {% endfor %}
                  </select>
                  {{ form.assistant.label_tag }}
                  <select id="id_{{ form.assistant.html_name }}" name="{{ form.assistant.html_name }}" class="form-control">
                      {% for assistant in assistants %}
                          <option value="{{ assistant.id }}"
                          {% if assistant.id == form.assistant.value|get_digit:"1"%}
                            selected="selected" {% endif %}>{{ assistant }}</option>
                      {% endfor %}
                  </select>
                  {{ form.venue.label_tag }}
                  <select id="id_{{ form.venue.html_name }}" name="{{ form.venue.html_name }}" class="form-control">
                      {% for address in addresses %}
                          <option value="{{ address.id }}"
                          {% if address.id == form.venue.value|get_digit:"1"%}
                            selected="selected" {% endif %}>{{ address.street }}{{ address.house }}</option>
                      {% endfor %}
                  </select>
                </div>
                <br>
                  {{ form.description.label_tag }}
                  

                  {{ form.description.errors }}
                  <textarea placeholder="Description" id="id_{{ form.description.html_name }}" name="{{ form.description.html_name }}" class="form-control" rows="3" >{{ form.description.value|default:'' }}</textarea>
          </div>
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <input type='submit' value="save" class="list-group-item bg-success"></a>
            <a href="" class="list-group-item bg-info">clean</a>
            <a href="{% url 'courses_list' %}" class="list-group-item bg-danger">cancel</a>
          </div>
        </div><!--/.sidebar-offcanvas-->
</form>

      </div><!--/row-->
  </div><!--/.container-->
{% endblock content %}

{% block js %}<script src="{{ STATIC_URL }}js/offcanvas.js"></script>{% endblock %}

templates/courses/courses_item.html
{% extends "courses/courses_base.html" %}
{% load static %}

{% block css %}{{ STATIC_URL }}courses_item.css{% endblock %}

{% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'courses_list' %}">Все курсы<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'courses_new' %}">Создать курс</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><b>Текущий:</b></li>
            <li><a href="{% url 'courses_edit' course.id %}">Редактирвоать</a></li>
            <li><a href="{% url 'courses_delete' course.id %}">Удалить</a></li>
            <li><a href="{% url 'group_new' %}">Создать группу</a></li>
          </ul>
          <ul class='nav nav-sidebar'>
            <li><b>Группы:</b></li>
            {% for group in course.group_set.all %}
              <li><a href="{% url 'groups_item' group.id %}">{{ group.name }}</a></li>
            {% empty %}
              <li>без групп</li>
            {% endfor %}
          </ul>
          </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block massage %} {{ block.super }} {% endblock massage %}
          <h1 class="page-header">{{ course.name }}</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{{ STATIC_URL }}img/page_{{ course.tecnology }}.png" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Технология</h4>
              <span class="text-muted">{{ course.tecnology }}</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{{ STATIC_URL }}img/2month.png" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Обучение - два месяца!</h4>
              <span class="text-muted">Мы все проверили! Это реально. Нечего сисю мять :)</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{{ STATIC_URL }}img/master.png" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>{{ course.coach.name }}
                {{ course.coach.surname }}</h4>
              <span class="text-muted">Преподаватель</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{{ STATIC_URL }}img/assistant.png" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>{{ course.assistant.name|default:'R2D2' }}
                {{ course.assistant.surname }}</h4>
              <span class="text-muted">Ассистент</span>
            </div>
          </div>
          <div class="row placeholders">
            <h2 class="sub-header">Описание курсов:</h2>
            <p class="sub-header" id='descr'>{{ course.description }}</p>
          </div>
        {% if course.student_set.all|length >= 1 %}
          <h3 class="sub-header">Список трудящихся студентов</h3>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Группа</th>
                  <th>Фамилия</th>
                  <th>Имя</th>
                  <th>Пакет</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
            {% for student in course.student_set.all %}
                <tr>
                  <td>
                    {% for group in student.group.all %}
                      {% if course.name in group.name %} 
                        {{ group.name }}
                      {% endif %}
                    {% endfor %}
                  </td>
                  <td>{{ student.surname }}</td>
                  <td>{{ student.name }}</td>
                  <td>{{ student.package }}</td>
                  <td><a href="{{ student.get_absolute_url }}">просмотреть
                  </td>
                </tr>
            {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <h3 class="sub-header">На этом курсе еще нет студентов.</h3>
        {% endif %}
        </div>
      </div>
    </div>

{% endblock content %}
{% block js %}
  <script src="../../assets/js/docs.min.js"></script>
{% endblock %}

templates/courses/courses_list.html
{% extends "courses/courses_base.html" %}
{% load static %}

{% block css %}{{ STATIC_URL }}courses_list.css{% endblock %}

{% block content %}
  <div class="container">

    <div class="container marketing">
{% block massage %}{{ block.super }}{% endblock massage %}
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Меню курсов</button>
          </p>
          <div class="jumbotron">
            <h1>Курсы!</h1>
            <p>Это иммитация списка курсов компинии IT Bursa. Их можно просмотреть, отредактировать, создать, и конечно удалить. Обязательно попробуйте сделать это сами.
          </div>
          <div class="row">
            {% for course in courses %}
              <div class="col-xs-6 col-lg-4">
                <a href="{% url 'courses_item' course.id %}">
                  <img class="img-rounded" src="{{ STATIC_URL }}img/{{ course.get_img }}" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                  <h2>{{ course.name }}</h2>
                </a>
                  <div class="btn-group">
                    <a  href="{% url 'courses_edit' course.id %}">
                      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                      <span style="color: green;">EDIT</span>
                    <a  href="{% url 'courses_delete' course.id %}">
                      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                  </div>
                <p>{{ course.description|truncatewords_html:6 }}</p>
              </div><!--/.col-xs-6.col-lg-4-->
            {% endfor %}
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="blog-sidebar sidebar-module sidebar-module-inset">
            <h4>И что нам с этим делать?</h4>
            <p>
              <br>После создания курса для него можно создавать группы по срокам обудечения и зачислять туда студентов.</p>
            </p>
          </div>
          <div class="list-group">
            <a href="{% url 'courses_new' %}" class="list-group-item">Создать курс</a>
          </div>
        </div>
      </div><!-- /.row -->
    </div>
  </div>
{% endblock content %}
    
{% block js %}<script src="{{ STATIC_URL }}js/offcanvas.js"></script>{% endblock %}

templates/courses/group_confirm_delete.html
{% extends "courses/courses_base.html" %}
{% load static %}

{% block css %}{{ STATIC_URL }}group_confirm_delete.css{% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <form action="" method="post">{% csrf_token %}
          <h3>Are you sure you want to delete {{ object.name }}
            {{ object.id }}</h3>
          <div class="btn-group" role="group" aria-label="...">
            <input type='submit' class='btn btn-danger' value="delete"/>
            <a href="{% url 'courses_list' %}" class="btn btn-default">cancel</a>
          </div>
        </form>
    </div>
{% endblock content %}

templates/courses/group_detail.html
{% extends "courses/courses_base.html" %}
{% load static %}

<!-- {% block css %}{{ STATIC_URL }}courses_item.css{% endblock %} -->

{% block content %}
    <div class="container">
      {% block massage %} {{ block.super }} {% endblock massage %}
      <h1>Gruop: {{ group.name }}</h1>
	  <div class="btn-group pull-right">
		  <a  href="{% url 'group_new' %}">
          <button class="btn btn-success" type="button">add group</button></a>
		  <a  href="{% url 'group_edit' group.id %}">
		    <button class="btn btn-warning  " type="button">edit</button></a>
		  <a  href="{% url 'group_delete' group.id %}">
		    <button class="btn btn-danger" type="button">delete</button></a>
	  </div>
		  {% if students|length >= 1 %}
			  <h2>enrolement of students:</h2>
		      <ol class="list-group">
		        {% for student in students %}
		        	
		        	<li class="list-group-item">{{ forloop.counter }} {{ student.name }}</li>
		        {% endfor %}
		        
		      </ol>
		  {% else %}
		   		<h2>Here is no studens</h2>
		  {% endif %} 		
    </div>
{% endblock content %}

templates/courses/group_edit.html
{% extends "courses/courses_base.html" %}
{% load static %}

{% block css %}{{ STATIC_URL }}group_edit.css{% endblock %}


{% block content %}
    <div class="container">
        {% block massage %} {{ block.super }} {% endblock massage %}
        <h1>Editing group</h1>
        <form method="post">
          {% csrf_token %}
          <ul class="list-group">
            {% for boundfield in form %}
              <li class="list-group-item">{{ boundfield.name }} {{ boundfield }}</li>
            {% endfor %}
          </ul>
          <div class="btn-group" role="group" aria-label="...">
            <input type='submit' class='btn btn-success' value="save"/>
            <a href=""<button type="button" class="btn btn-info">clean</button></a>
            <a href="{% url 'courses_list' %}" class="btn btn-default">cancel</a>
            {% if object %}
            <a href="{% url 'group_delete' object.id %}" class="btn btn-warning">delete</a>
            {% endif %}
          </div>
        </form>
    </div>
{% endblock content %}